on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: sample job
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: tarappo/sample-composite-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: echo "GITHUB_REF_NAMEï¼š${{ $GITHUB_REF_NAME }}"
        shell: bash
